BaseUrl= "http://geee-uefs.github.io/blog/"
LanguageCode= "pt-BR"
Title= "Blog"
paginate = 5
DisqusShortname = "geee-uefs"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Val√®re JEANTET"
  authorlocation = "Paris, France"
  authorwebsite = "http://github.com/geee-uefs"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "geee-uefs"
  twitterName = "geee-uefs"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
